//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KB.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public Record()
        {
            this.Attachments = new HashSet<Attachment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Desc { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual Category Category { get; set; }
    }
}
